#include "../../ShaderLibrary/ScreenSpaceReprojection.hlsl"
float4x4 Matrix_HistoryViewProj, Matrix_MotionViewProj, Matrix_LastMotionViewProj;
#include "../../ShaderLibrary/BSDF.hlsl"
#include "../../ShaderLibrary/ColorUtility.hlsl"
#include "../../ShaderLibrary/RayTracing/ScreenSpaceRayTrace/SSRTRayCast.hlsl"

float4x4 Matrix_Proj, Matrix_InvProj, Matrix_ViewProj, Matrix_InvViewProj, Matrix_WorldToView;
Texture2D SRV_PyramidColor, SRV_PyramidDepth, SRV_SceneDepth, SRV_GBufferNormal;
int SSGi_RayMask, SSGi_FrameIndex, SSGi_NumRays, SSGi_NumSteps;
float SSGi_MaxDistance;
float SSGi_Thickness, SSGi_Intensity;
float4 SSGi_HZBUvFactor, SSGi_TraceResolution;
RWTexture2D<float4> UAV_ScreenIrradiance;

#pragma kernel Raytracing
[numthreads(16, 16, 1)]
void Raytracing (uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= (uint2)SSGi_TraceResolution.xy)) return;
    float2 UV = (id.xy + 0.5) * SSGi_TraceResolution.zw;
	uint2 PixelPosition = uint2(UV.xy * SSGi_TraceResolution.xy);

	float SceneDepth = SRV_SceneDepth.SampleLevel(Global_point_clamp_sampler, UV, 0).r;
    if (ScreenSpaceIsFarDepth(SceneDepth)) {
        UAV_ScreenIrradiance[id.xy] = 0;
        return;
    }
	float3 NDCPos = GetNDCPos(UV, SceneDepth);
	float3 WorldPos = GetWorldSpacePos(NDCPos, Matrix_InvViewProj);
	float3 ViewPos = GetViewSpacePos(NDCPos, Matrix_InvProj);
	float3 ViewDir = GetViewDir(WorldPos, ViewPos);
	float3 WorldNormal = normalize(SRV_GBufferNormal.SampleLevel(Global_point_clamp_sampler, UV, 0).xyz * 2 - 1);
	float3x3 TangentToWorld = GetTangentBasis(WorldNormal);

	uint FrameIDMod8 = uint(fmod(SSGi_FrameIndex, 32));
	uint2 Random = Rand3DPCG16( uint3(PixelPosition, FrameIDMod8) ).xy;
	float StepOffset = InterleavedGradientNoise(PixelPosition + 0.5, FrameIDMod8) - 0.9;

    float4 Out_ColorMask = 0;

	[loop]
	for (uint i = 0; i < (uint)SSGi_NumRays; i++)
	{
		float2 Hash = Hammersley16(i, (uint)SSGi_NumRays, Random);
		float3 LightDir_TS = CosineSampleHemisphere(Hash).xyz;
		float3 LightDir_WS = mul(LightDir_TS, TangentToWorld);
		float3 LightDir_VS = mul((float3x3)(Matrix_WorldToView), LightDir_WS);

        float3 HitUVz;
        bool bHit = TraceScreenSpaceRay(ViewPos, normalize(LightDir_VS), SSGi_MaxDistance, SSGi_Thickness,
            (uint)SSGi_NumSteps, StepOffset + 0.9, Matrix_Proj, SRV_PyramidDepth, HitUVz);

		[branch]
		if(bHit)
		{
			float3 SampleNormal = SRV_GBufferNormal.SampleLevel(Global_point_clamp_sampler, HitUVz.xy, 0).xyz * 2 - 1;

			float3 SampleColor = SRV_PyramidColor.SampleLevel(Global_point_clamp_sampler, HitUVz.xy, 0).rgb;
			SampleColor.rgb *= saturate(-dot(LightDir_WS, normalize(SampleNormal)));
			float confidence = GetScreenFadeBord(HitUVz.xy, 0.1);
            Out_ColorMask += float4(SampleColor.rgb * confidence, confidence);

		}
	}

	Out_ColorMask /= SSGi_NumRays;
	Out_ColorMask *= SSGi_Intensity;
	UAV_ScreenIrradiance[id.xy] = Out_ColorMask;
}

float4x4 Matrix_LastViewProj;
float SSGi_SpatialRadius, SSGi_TemporalScale, SSGi_TemporalWeight;
float4 SSGi_FilterResolution;
Texture2D SRV_MotionTexture, SRV_ColorMaskTexture, SRV_AliasingTexture, SRV_HistoryTexture, SRV_HistoryMoments, SRV_HistoryDepthNormal;

static const int2 SSGI_SpatialOffset[15] = { int2(0, 1), int2(-2, 1), int2(2, -3), int2(-3, 0), int2(1, 2), int2(-1, -2), int2(3, 0), int2(-3, 3), int2(0, -3), int2(-1, -1), int2(2, 1), int2(-2, -2), int2(1, 0), int2(0, 2), int2(3, -1) };

#pragma kernel SpatialFilter
RWTexture2D<float4> UAV_SpatialTexture;
[numthreads(16, 16, 1)]
void SpatialFilter(uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= (uint2)SSGi_FilterResolution.xy)) return;
    float2 UV = (id.xy + 0.5) * SSGi_FilterResolution.zw;
    float SceneDepth = SRV_SceneDepth.SampleLevel(Global_point_clamp_sampler, UV, 0).r;
    if (ScreenSpaceIsFarDepth(SceneDepth))
    {
        UAV_SpatialTexture[id.xy] = 0;
        return;
    }

    float3 WorldNormal = normalize(SRV_GBufferNormal.SampleLevel(Global_point_clamp_sampler, UV, 0).xyz * 2 - 1);
    float NumWeight = 1;
    float4 SpatialColor = SRV_ColorMaskTexture.SampleLevel(Global_point_clamp_sampler, UV, 0);

    [loop]
    for (int i = 0; i < 15; ++i)
    {
        float2 Offset_UV = UV + (SSGI_SpatialOffset[i] * SSGi_FilterResolution.zw * SSGi_SpatialRadius);
        if (any(Offset_UV < 0) || any(Offset_UV >= 1)) continue;
        if (any(Offset_UV < 0) || any(Offset_UV >= 1)) continue;
        float OffsetDepth = SRV_SceneDepth.SampleLevel(Global_point_clamp_sampler, Offset_UV, 0).r;
        float3 OffsetNormal = normalize(SRV_GBufferNormal.SampleLevel(Global_point_clamp_sampler, Offset_UV, 0).xyz * 2 - 1);
        float4 HitColorMask = SRV_ColorMaskTexture.SampleLevel(Global_bilinear_clamp_sampler, Offset_UV, 0);
        float Weight = ScreenSpaceDepthWeight(ScreenSpaceLinearEyeDepth(SceneDepth), ScreenSpaceLinearEyeDepth(OffsetDepth), max(SSGi_Thickness, ScreenSpaceLinearEyeDepth(SceneDepth) * 0.01)) * ScreenSpaceNormalWeight(WorldNormal, OffsetNormal, 32);
        NumWeight += Weight;
        SpatialColor += HitColorMask * Weight;
    }

    SpatialColor /= max(NumWeight, 1e-5);
    UAV_SpatialTexture[id.xy] = SpatialColor;
}

#define SSGI_VARIANCE_THRESHOLD 0.0005
static const int2 SSGI_TemporalOffset[9] = { int2(-1, -1), int2(0, -1), int2(1, -1), int2(-1, 0), int2(0, 0), int2(1, 0), int2(-1, 1), int2(0, 1), int2(1, 1) };

#pragma kernel TemporalFilter
RWTexture2D<float4> UAV_AccmulateTexture;
RWTexture2D<float4> UAV_MomentsTexture;
RWTexture2D<float4> UAV_DepthNormalTexture;
[numthreads(16, 16, 1)]
void TemporalFilter(uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= (uint2)SSGi_FilterResolution.xy)) return;
    float2 UV = (id.xy + 0.5) * SSGi_FilterResolution.zw;
    float SceneDepth = SRV_SceneDepth.SampleLevel(Global_point_clamp_sampler, UV, 0).r;
    float3 WorldNormal = normalize(SRV_GBufferNormal.SampleLevel(Global_point_clamp_sampler, UV, 0).xyz * 2 - 1);
    float2 DepthMotion = SRV_MotionTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).xy;

    float4 SampleColors[9];
    float4 CurrColor, PrevColor, MomentA = 0, MomentB = 0;
    [loop]
    for (int i = 0; i < 9; ++i)
    {
        SampleColors[i] = SRV_AliasingTexture.SampleLevel(Global_bilinear_clamp_sampler, UV + (SSGI_TemporalOffset[i] * SSGi_FilterResolution.zw), 0);
        MomentA += SampleColors[i];
        MomentB += SampleColors[i] * SampleColors[i];
    }

    float4 Mean = MomentA / 9;
    float4 Stddev = sqrt(max(0, (MomentB / 9) - pow2(Mean)));
    CurrColor = SampleColors[4];
    float4 MinColor = min(Mean - SSGi_TemporalScale * Stddev, CurrColor);
    float4 MaxColor = max(Mean + SSGi_TemporalScale * Stddev, CurrColor);

    float2 PrevUV;
    float expectedHistoryDepth;
    ReprojectSurface(UV, SceneDepth, DepthMotion, Matrix_InvViewProj, Matrix_HistoryViewProj, Matrix_MotionViewProj, Matrix_LastMotionViewProj, PrevUV, expectedHistoryDepth);
    bool offscreen = any(PrevUV < 0) || any(PrevUV > 1);
    if (offscreen)
    {
        PrevColor = CurrColor;
    }
    else
    {
        float4 HistoryDepthNormal = SRV_HistoryDepthNormal.SampleLevel(Global_point_clamp_sampler, PrevUV, 0);
        float3 HistoryNormal = HistoryDepthNormal.xyz * 2 - 1;
        float DepthConfidence = HistoryDepthConfidence(SRV_HistoryDepthNormal, PrevUV, expectedHistoryDepth, 3);
        float NormalReject = 1 - saturate(dot(WorldNormal, HistoryNormal));
        float HistoryConfidence = DepthConfidence * saturate(1 - NormalReject * 4);
        PrevColor = clamp(SRV_HistoryTexture.SampleLevel(Global_point_clamp_sampler, PrevUV, 0), MinColor, MaxColor);
        PrevColor = lerp(CurrColor, PrevColor, HistoryConfidence);
    }

    float BlendWeight = clamp(lerp(SSGi_TemporalWeight, 0.0, length(DepthMotion) * 200.0), 0.0, SSGi_TemporalWeight);
    float4 Radiance = max(0, lerp(CurrColor, PrevColor, BlendWeight));
    float historyLuma = Rec709Luminance(PrevColor.rgb);
    float luma = Rec709Luminance(Radiance.rgb);
    float Variance = (abs(historyLuma - luma) / max(max(historyLuma, luma), 1e-5)) > SSGI_VARIANCE_THRESHOLD ? 0 : 1;

    UAV_AccmulateTexture[id.xy] = Radiance;
    UAV_MomentsTexture[id.xy] = float4(Rec709Luminance(Mean.rgb), Rec709Luminance(Stddev.rgb), BlendWeight, Variance);
    UAV_DepthNormalTexture[id.xy] = float4(WorldNormal * 0.5 + 0.5, SceneDepth);
}

static const float SSGI_BilateralKernel[25] = { 1.0 / 256.0, 1.0 / 64.0, 3.0 / 128.0, 1.0 / 64.0, 1.0 / 256.0, 1.0 / 64.0, 1.0 / 16.0, 3.0 / 32.0, 1.0 / 16.0, 1.0 / 64.0, 3.0 / 128.0, 3.0 / 32.0, 9.0 / 64.0, 3.0 / 32.0, 3.0 / 128.0, 1.0 / 64.0, 1.0 / 16.0, 3.0 / 32.0, 1.0 / 16.0, 1.0 / 64.0, 1.0 / 256.0, 1.0 / 64.0, 3.0 / 128.0, 1.0 / 64.0, 1.0 / 256.0 };
static const int2 SSGI_BilateralOffset[25] = { int2(-2, -2), int2(-1, -2), int2(0, -2), int2(1, -2), int2(2, -2), int2(-2, -1), int2(-1, -1), int2(0, -1), int2(1, -1), int2(2, -1), int2(-2, 0), int2(-1, 0), int2(0, 0), int2(1, 0), int2(2, 0), int2(-2, 1), int2(-1, 1), int2(0, 1), int2(1, 1), int2(2, 1), int2(-2, 2), int2(-1, 2), int2(0, 2), int2(1, 2), int2(2, 2) };

float SVGF_BilateralRadius, SVGF_ColorWeight, SVGF_NormalWeight, SVGF_DepthWeight;
float4 SVGF_BilateralSize;

#pragma kernel BilateralFilter
RWTexture2D<float4> UAV_BilateralColor;
[numthreads(16, 16, 1)]
void BilateralFilter(uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= (uint2)SVGF_BilateralSize.xy)) return;
    float WeightSum = 0;
    float4 ColorSum = 0;
    float2 UV = (id.xy + 0.5) * SVGF_BilateralSize.zw;
    float4 Color = SRV_AliasingTexture.SampleLevel(Global_bilinear_clamp_sampler, UV, 0);
    float4 Normal = SRV_GBufferNormal.SampleLevel(Global_bilinear_clamp_sampler, UV, 0);
    float Depth = ScreenSpaceLinearEyeDepth(SRV_SceneDepth.SampleLevel(Global_point_clamp_sampler, UV, 0).r);

    for (int i = 0; i < 25; ++i)
    {
        float2 OffsetUV = UV + (SSGI_BilateralOffset[i] * SVGF_BilateralSize.zw * SVGF_BilateralRadius);
        float4 OffsetColor = SRV_AliasingTexture.SampleLevel(Global_bilinear_clamp_sampler, OffsetUV, 0);
        float4 OffsetNormal = SRV_GBufferNormal.SampleLevel(Global_bilinear_clamp_sampler, OffsetUV, 0);
        float OffsetDepth = ScreenSpaceLinearEyeDepth(SRV_SceneDepth.SampleLevel(Global_point_clamp_sampler, OffsetUV, 0).r);

        float4 Distance = Normal - OffsetNormal;
        float Distance2 = max(dot(Distance, Distance) / max(SVGF_BilateralRadius * SVGF_BilateralRadius, 1e-4), 0);
        float WeightNormal = min(exp(-Distance2 / max(SVGF_NormalWeight, 1e-4)), 1);
        float WeightDepth = (SVGF_DepthWeight == 0) ? 0 : abs(Depth - OffsetDepth) / SVGF_DepthWeight;
        float WeightColor = abs(Rec709Luminance(Color.rgb) - Rec709Luminance(OffsetColor.rgb)) / max(SVGF_ColorWeight, 1e-4);
        float Weight = exp(0 - max(WeightColor, 0) - max(WeightDepth, 0)) * WeightNormal;
        ColorSum += OffsetColor * Weight * SSGI_BilateralKernel[i];
        WeightSum += Weight * SSGI_BilateralKernel[i];
    }

    UAV_BilateralColor[id.xy] = ColorSum / max(WeightSum, 1e-5);
}
