#include "../../ShaderLibrary/ScreenSpaceReprojection.hlsl"
float4x4 Matrix_HistoryViewProj, Matrix_MotionViewProj, Matrix_LastMotionViewProj;
#include "../../ShaderLibrary/BSDF.hlsl"
#include "../../ShaderLibrary/Random.hlsl"
#include "../../ShaderLibrary/Common.hlsl"
#include "../../ShaderLibrary/RayTracing/Variance/VarianceEstimator.hlsl"
#include "../../ShaderLibrary/RayTracing/ScreenSpaceRayTrace/SSRTRayCast.hlsl"

int SSR_NumRays, SSR_NumSteps, SSR_FrameIndex;
float SSR_MaxDistance;
float SSR_BRDFBias, SSR_Thickness, SSR_Fadeness, SSR_Roughness, SSR_SpatialRadius, SSR_TemporalScale, SSR_TemporalWeight, ColorPyramidNumLOD;
float4 SSR_Resolution, SSR_FilterResolution;
float4x4 Matrix_Proj, Matrix_InvProj, Matrix_InvViewProj, Matrix_WorldToView;
Texture2D SRV_DepthTexture, SRV_MotionTexture, SRV_NormalTexture, SRV_RoughnessTexture, SRV_HiCTexture, SRV_HiZTexture, SRV_HitPDFTexture, SRV_ColorMaskTexture, SRV_AliasingTexture, SRV_HistoryTexture, SRV_HistoryMoments, SRV_HistoryDepthNormal;

static const float2 kStackowiakSampleSet0[56 * 4] =
{
	float2(-0.5, -0.5), float2(+0.5, -0.5), float2(-0.5, +0.5), float2(+0.5, +0.5),
	float2(-1.5, +0.5), float2(-1.5, -0.5), float2(-0.5, +1.5), float2(+1.5, -0.5),
	float2(+0.5, -1.5), float2(+2.5, -0.5), float2(+1.5, +0.5), float2(-0.5, -1.5),
	float2(-1.5, -2.5), float2(-0.5, -2.5), float2(-1.5, -1.5), float2(-0.5, +2.5),
	float2(-1.5, +1.5), float2(+1.5, -2.5), float2(-1.5, +2.5), float2(+1.5, +2.5),
	float2(+0.5, -2.5), float2(-2.5, -0.5), float2(-2.5, -1.5), float2(-2.5, +0.5),
	float2(+0.5, +1.5), float2(+0.5, +2.5), float2(-3.5, +0.5), float2(+0.5, +3.5),
	float2(+1.5, -1.5), float2(+3.5, -0.5), float2(+2.5, +1.5), float2(+3.5, +0.5),
	float2(+1.5, +1.5), float2(-2.5, +1.5), float2(-3.5, +2.5), float2(+3.5, +1.5),
	float2(-3.5, -0.5), float2(-1.5, -3.5), float2(-2.5, -2.5), float2(-2.5, +2.5),
	float2(+2.5, +0.5), float2(+2.5, +2.5), float2(+1.5, +3.5), float2(+3.5, -1.5),
	float2(-3.5, -2.5), float2(+3.5, -2.5), float2(+2.5, -1.5), float2(+0.5, -3.5),
	float2(-0.5, +3.5), float2(-0.5, -4.5), float2(-4.5, +0.5), float2(+4.5, +0.5),
	float2(-4.5, -1.5), float2(-3.5, +1.5), float2(-0.5, -3.5), float2(+1.5, -3.5),
	float2(+0.5, -4.5), float2(-1.5, +3.5), float2(+0.5, +4.5), float2(-3.5, -1.5),
	float2(-4.5, +1.5), float2(+2.5, -4.5), float2(+2.5, -2.5), float2(-1.5, +4.5),
	float2(-2.5, -4.5), float2(+4.5, -2.5), float2(+2.5, +3.5), float2(-3.5, +3.5),
	float2(-2.5, +3.5), float2(+0.5, -5.5), float2(-4.5, +3.5), float2(-2.5, -3.5),
	float2(-4.5, +2.5), float2(+3.5, +3.5), float2(+2.5, -3.5), float2(+4.5, +3.5),
	float2(+3.5, -3.5), float2(+4.5, +2.5), float2(-5.5, +1.5), float2(-4.5, -0.5),
	float2(+3.5, +2.5), float2(-0.5, +4.5), float2(-1.5, +5.5), float2(+1.5, +5.5),
	float2(+4.5, -0.5), float2(+5.5, +0.5), float2(+4.5, +1.5), float2(-1.5, -4.5),
	float2(-1.5, -5.5), float2(-4.5, -2.5), float2(-2.5, +5.5), float2(+2.5, +5.5),
	float2(+1.5, +4.5), float2(+5.5, +1.5), float2(+1.5, -4.5), float2(-3.5, -3.5),
	float2(+3.5, -4.5), float2(-3.5, -4.5), float2(+4.5, -1.5), float2(+4.5, -3.5),
	float2(-3.5, -5.5), float2(-2.5, -5.5), float2(-4.5, -3.5), float2(+4.5, +4.5),
	float2(-3.5, +4.5), float2(-2.5, +4.5), float2(-5.5, -2.5), float2(-5.5, +0.5),
	float2(+2.5, -5.5), float2(+3.5, +4.5), float2(-0.5, -5.5), float2(-0.5, +6.5),
	float2(+2.5, +4.5), float2(-5.5, -0.5), float2(-6.5, -1.5), float2(+1.5, -5.5),
	float2(-6.5, -0.5), float2(+0.5, +5.5), float2(+1.5, +6.5), float2(+6.5, +1.5),
	float2(-0.5, +5.5), float2(+6.5, -0.5), float2(-4.5, -4.5), float2(-5.5, +2.5),
	float2(+5.5, -0.5), float2(-5.5, -1.5), float2(-6.5, +3.5), float2(-1.5, +6.5),
	float2(-6.5, +0.5), float2(+4.5, -5.5), float2(-3.5, +6.5), float2(+6.5, -1.5),
	float2(+0.5, -6.5), float2(-5.5, -3.5), float2(+5.5, -2.5), float2(+4.5, -4.5),
	float2(+5.5, -1.5), float2(+3.5, -6.5), float2(+5.5, +3.5), float2(+3.5, -5.5),
	float2(-5.5, -4.5), float2(+6.5, -3.5), float2(-0.5, -6.5), float2(+3.5, +6.5),
	float2(-5.5, +3.5), float2(+0.5, +6.5), float2(+6.5, +0.5), float2(+6.5, -2.5),
	float2(-6.5, -3.5), float2(-4.5, +4.5), float2(-7.5, -0.5), float2(+7.5, +0.5),
	float2(+5.5, +2.5), float2(-0.5, -7.5), float2(+0.5, +7.5), float2(-4.5, +5.5),
	float2(+3.5, +5.5), float2(-3.5, +5.5), float2(-4.5, -5.5), float2(+4.5, +6.5),
	float2(+5.5, -4.5), float2(+4.5, +5.5), float2(-4.5, +6.5), float2(+6.5, +4.5),
	float2(-7.5, +1.5), float2(-6.5, +1.5), float2(+5.5, -3.5), float2(-6.5, +2.5),
	float2(-2.5, +6.5), float2(-1.5, -7.5), float2(+5.5, +4.5), float2(-1.5, -6.5),
	float2(-3.5, -7.5), float2(+2.5, -7.5), float2(-7.5, +2.5), float2(-6.5, -2.5),
	float2(-5.5, +5.5), float2(+2.5, +6.5), float2(-2.5, -6.5), float2(-7.5, +0.5),
	float2(-0.5, +7.5), float2(+7.5, -2.5), float2(-2.5, +7.5), float2(+0.5, -7.5),
	float2(-4.5, -7.5), float2(+7.5, +1.5), float2(+1.5, -6.5), float2(-6.5, +4.5),
	float2(-1.5, +7.5), float2(-5.5, -5.5), float2(+6.5, +2.5), float2(-3.5, -6.5),
	float2(+3.5, -7.5), float2(-5.5, +4.5), float2(+2.5, -6.5), float2(+1.5, -7.5),
	float2(+6.5, +3.5), float2(+5.5, -6.5), float2(-6.5, +5.5), float2(+7.5, +4.5),
	float2(+7.5, -1.5), float2(-7.5, -1.5), float2(+3.5, +7.5), float2(-5.5, +6.5),
	float2(+1.5, +7.5), float2(+7.5, +3.5), float2(+7.5, -0.5), float2(-7.5, -2.5),
	float2(+5.5, +5.5), float2(+6.5, +5.5), float2(+5.5, -5.5), float2(-2.5, -7.5),
	float2(+2.5, +7.5), float2(-7.5, -3.5), float2(-7.5, -4.5), float2(-6.5, -4.5),
	float2(+7.5, -3.5), float2(+5.5, +6.5), float2(-5.5, -6.5), float2(-4.5, -6.5),
	float2(+7.5, +2.5), float2(-7.5, +3.5), float2(+4.5, -6.5), float2(+7.5, -4.5),
};
static const float2 kStackowiakSampleSet1[56 * 4] =
{
    float2(-0.5, -0.5), float2(+0.5, -0.5), float2(-0.5, +0.5), float2(+0.5, +0.5),
    float2(+0.5, -1.5), float2(+1.5, -1.5), float2(-1.5, -0.5), float2(+1.5, +1.5),
    float2(-0.5, -2.5), float2(-1.5, -1.5), float2(+0.5, +1.5), float2(-1.5, +0.5),
    float2(+1.5, -0.5), float2(-0.5, +1.5), float2(-2.5, +0.5), float2(+0.5, +2.5),
    float2(-2.5, -1.5), float2(+2.5, +0.5), float2(+1.5, +0.5), float2(-0.5, -1.5),
    float2(-1.5, +1.5), float2(+2.5, -2.5), float2(-3.5, -0.5), float2(-1.5, +2.5),
    float2(-2.5, +1.5), float2(-2.5, -0.5), float2(-1.5, -2.5), float2(+2.5, -1.5),
    float2(-3.5, +0.5), float2(-0.5, -3.5), float2(-1.5, +3.5), float2(+0.5, -2.5),
    float2(+1.5, +2.5), float2(-0.5, +2.5), float2(+0.5, +3.5), float2(+3.5, +0.5),
    float2(+2.5, +1.5), float2(-2.5, -2.5), float2(+2.5, -0.5), float2(+3.5, -1.5),
    float2(-0.5, +3.5), float2(+3.5, +1.5), float2(-3.5, +2.5), float2(+3.5, +2.5),
    float2(+3.5, -0.5), float2(+0.5, -4.5), float2(-2.5, +3.5), float2(+0.5, -3.5),
    float2(-1.5, -4.5), float2(+1.5, +3.5), float2(+1.5, -2.5), float2(-3.5, +1.5),
    float2(+2.5, -3.5), float2(-2.5, -3.5), float2(+2.5, +2.5), float2(+1.5, +4.5),
    float2(-4.5, -2.5), float2(-2.5, +2.5), float2(-4.5, +1.5), float2(+4.5, +1.5),
    float2(-2.5, -4.5), float2(+3.5, -3.5), float2(-1.5, -3.5), float2(-3.5, -1.5),
    float2(+1.5, -4.5), float2(+4.5, -2.5), float2(+1.5, -3.5), float2(-1.5, +4.5),
    float2(-4.5, +2.5), float2(-4.5, -0.5), float2(+2.5, +4.5), float2(-4.5, +0.5),
    float2(-3.5, -4.5), float2(+0.5, +4.5), float2(+3.5, -2.5), float2(-3.5, -2.5),
    float2(-3.5, +3.5), float2(+3.5, +3.5), float2(+4.5, +0.5), float2(+0.5, +5.5),
    float2(-0.5, +4.5), float2(+4.5, -3.5), float2(-1.5, +5.5), float2(-0.5, -4.5),
    float2(+2.5, +3.5), float2(+4.5, +2.5), float2(-2.5, +5.5), float2(+2.5, -4.5),
    float2(+4.5, -0.5), float2(+5.5, -0.5), float2(-4.5, +4.5), float2(+5.5, -1.5),
    float2(-5.5, -1.5), float2(-4.5, -1.5), float2(+3.5, +4.5), float2(-3.5, -3.5),
    float2(-5.5, +0.5), float2(+1.5, -5.5), float2(-5.5, -2.5), float2(-3.5, +4.5),
    float2(+0.5, -5.5), float2(-2.5, -5.5), float2(+2.5, +5.5), float2(+4.5, +4.5),
    float2(+4.5, -1.5), float2(-2.5, +4.5), float2(+4.5, +3.5), float2(+0.5, +6.5),
    float2(-0.5, -6.5), float2(+5.5, +2.5), float2(-0.5, -5.5), float2(-5.5, -0.5),
    float2(-6.5, -1.5), float2(-0.5, +5.5), float2(-0.5, +6.5), float2(+6.5, -0.5),
    float2(+1.5, +5.5), float2(+1.5, -6.5), float2(+5.5, +0.5), float2(-5.5, +2.5),
    float2(+5.5, +1.5), float2(-5.5, +1.5), float2(-6.5, -0.5), float2(-1.5, -5.5),
    float2(-5.5, -4.5), float2(-4.5, +3.5), float2(-6.5, +1.5), float2(+2.5, -5.5),
    float2(+3.5, -5.5), float2(-5.5, -3.5), float2(+1.5, +6.5), float2(+6.5, +2.5),
    float2(+4.5, -4.5), float2(+3.5, -6.5), float2(-4.5, -4.5), float2(-4.5, -3.5),
    float2(-6.5, +2.5), float2(+3.5, +5.5), float2(+3.5, -4.5), float2(+5.5, -3.5),
    float2(-5.5, +4.5), float2(+6.5, -3.5), float2(-6.5, -2.5), float2(+5.5, +4.5),
    float2(-1.5, +6.5), float2(-0.5, -7.5), float2(-6.5, +3.5), float2(-5.5, +3.5),
    float2(-6.5, -4.5), float2(+7.5, -1.5), float2(-3.5, -5.5), float2(+3.5, +6.5),
    float2(+5.5, +3.5), float2(+7.5, +0.5), float2(+5.5, -2.5), float2(-6.5, +0.5),
    float2(-7.5, +1.5), float2(-3.5, -6.5), float2(+6.5, +0.5), float2(+7.5, +1.5),
    float2(-2.5, -7.5), float2(-3.5, +5.5), float2(-7.5, -0.5), float2(-3.5, +6.5),
    float2(-2.5, +6.5), float2(+4.5, -6.5), float2(-5.5, +5.5), float2(+4.5, -5.5),
    float2(+6.5, -2.5), float2(+6.5, +3.5), float2(-1.5, -6.5), float2(-1.5, +7.5),
    float2(+6.5, +1.5), float2(-5.5, -5.5), float2(+0.5, -6.5), float2(+7.5, +3.5),
    float2(+2.5, +6.5), float2(-4.5, +5.5), float2(-6.5, -3.5), float2(-4.5, -5.5),
    float2(-6.5, -5.5), float2(+5.5, -6.5), float2(-2.5, -6.5), float2(+5.5, -5.5),
    float2(+4.5, +5.5), float2(-7.5, +0.5), float2(+6.5, -1.5), float2(+0.5, -7.5),
    float2(+7.5, -0.5), float2(-3.5, -7.5), float2(+2.5, -6.5), float2(-3.5, +7.5),
    float2(-4.5, -7.5), float2(-0.5, +7.5), float2(-6.5, +5.5), float2(+7.5, -3.5),
    float2(-4.5, +6.5), float2(+1.5, +7.5), float2(+5.5, -4.5), float2(+7.5, +4.5),
    float2(+0.5, +7.5), float2(+4.5, +6.5), float2(-4.5, +7.5), float2(-7.5, -1.5),
    float2(+3.5, -7.5), float2(+7.5, -4.5), float2(+3.5, +7.5), float2(-1.5, -7.5),
    float2(+6.5, -4.5), float2(-7.5, -3.5), float2(+6.5, +4.5), float2(+2.5, -7.5),
    float2(+7.5, -2.5), float2(-7.5, +2.5), float2(+1.5, -7.5), float2(-5.5, +6.5),
    float2(+5.5, +5.5), float2(-2.5, +7.5), float2(+7.5, +2.5), float2(-7.5, -2.5),
    float2(+2.5, +7.5), float2(-6.5, +4.5), float2(+5.5, +6.5), float2(-4.5, -6.5),
};
static const int2 kStackowiakSampleSet2[16] = {int2(0, 0), int2(0, 1), int2(1, 0), int2(1, 1), int2(0, -1), int2(-1, -2), int2(-1, 0), int2(0, 2), int2(1, -1), int2(-1, 1), int2(-1, 2), int2(1, 2), int2(2, -1), int2(2, 0), int2(2, 1), int2(2, 2)};
static const int2 kStackowiakSampleSet3[9] = { int2(0, 0), int2(1, -1), int2(-1, -1), int2(0, 1), int2(1, 0), int2(1, 1), int2(0, -1), int2(-1, 0), int2(-1, 1) };
static const int2 kStackowiakSampleSet4[15] = { int2(0, 1), int2(-2, 1), int2(2, -3), int2(-3, 0), int2(1, 2), int2(-1, -2), int2(3, 0), int2(-3, 3), int2(0, -3), int2(-1, -1), int2(2, 1), int2(-2, -2), int2(1, 0), int2(0, 2), int2(3, -1) };
static const int2 kStackowiakSampleSet5[4] = { int2(0, 0), int2(0, 1), int2(1, 0), int2(1, 1) };

#pragma kernel Raytracing
RWTexture2D<float4> UAV_HitPDFTexture;
RWTexture2D<float4> UAV_ColorMaskTexture;
[numthreads(16, 16, 1)]
void Raytracing(uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= (uint2)SSR_Resolution.xy)) return;
    float2 UV = (id.xy + 0.5) * SSR_Resolution.zw;
    uint2 PixelPosition = uint2(UV.xy * SSR_Resolution.xy);

    float SceneDepth = SRV_DepthTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).r;
    if (ScreenSpaceIsFarDepth(SceneDepth))
    {
        UAV_HitPDFTexture[id.xy] = 0;
        UAV_ColorMaskTexture[id.xy] = 0;
        return;
    }
    float Roughness = SRV_RoughnessTexture.SampleLevel(Global_bilinear_clamp_sampler, UV, 0).b;
    Roughness = clamp(Roughness, 0.02, 1);
    if (Roughness > SSR_Roughness)
    {
        UAV_HitPDFTexture[id.xy] = 0;
        UAV_ColorMaskTexture[id.xy] = 0;
        return;
    }
    float3 NDCPos = GetNDCPos(UV, SceneDepth);
    float3 ViewPos = GetViewSpacePos(NDCPos, Matrix_InvProj);
    float3 WorldNormal = normalize(SRV_NormalTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).xyz * 2 - 1);
    float3x3 TangentToWorld = GetTangentBasis(WorldNormal);

    uint FrameIDMod8 = uint(fmod(SSR_FrameIndex, 8));
    uint2 Random = Rand3DPCG16(uint3(PixelPosition, FrameIDMod8)).xy;
    float StepOffset = InterleavedGradientNoise(PixelPosition + 0.5, FrameIDMod8) - 0.9;

    float4 Out_UVWPDF = 0;
    float4 Out_ColorMask = 0;

    [loop]
    for (uint i = 0; i < (uint)SSR_NumRays; ++i)
    {
        float2 Hash = Hammersley16(i, (uint)SSR_NumRays, Random);
        Hash.y = lerp(Hash.y, 0, SSR_BRDFBias);
        float4 LightDir_TS = ImportanceSampleGGX(Hash, Roughness);
        float3 LightDir_WS = mul(LightDir_TS.xyz, TangentToWorld);
        float3 LightDir_VS = mul((float3x3)(Matrix_WorldToView), LightDir_WS);
        LightDir_VS = reflect(-ScreenSpaceViewDirection(ViewPos), LightDir_VS);
        if (dot(LightDir_VS, mul((float3x3)Matrix_WorldToView, WorldNormal)) <= 0) continue;

        float3 HitUVz;
        bool bHit = TraceScreenSpaceRay(ViewPos, normalize(LightDir_VS), SSR_MaxDistance, SSR_Thickness,
            (uint)SSR_NumSteps, StepOffset + 0.9, Matrix_Proj, SRV_HiZTexture, HitUVz);

        [branch]
        if (bHit)
        {
            if (Out_UVWPDF.w == 0) Out_UVWPDF = float4(HitUVz, max(LightDir_TS.w, 1e-5));
            float3 SampleColor = SRV_HiCTexture.SampleLevel(Global_bilinear_clamp_sampler, HitUVz.xy, 0).rgb;
            float confidence = GetScreenFadeBord(HitUVz.xy, SSR_Fadeness);
            Out_ColorMask += float4(SampleColor.rgb * confidence, confidence);
        }
    }


    Out_ColorMask *= rcp(SSR_NumRays);
    Out_ColorMask.a = saturate(Out_ColorMask.a);

    UAV_HitPDFTexture[id.xy] = Out_UVWPDF;
    UAV_ColorMaskTexture[id.xy] = Out_ColorMask ;
}

#define SSR_NumSpatial 15

#pragma kernel SpatialFilter
RWTexture2D<float4> UAV_SpatialTexture;
[numthreads(16, 16, 1)]
void SpatialFilter (uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= (uint2)SSR_FilterResolution.xy)) return;
    float2 UV = (id.xy + 0.5) * SSR_FilterResolution.zw;
    uint2 PixelPosition = uint2(UV.xy * SSR_FilterResolution.xy);
	float SceneDepth = SRV_DepthTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).r;
    if (ScreenSpaceIsFarDepth(SceneDepth))
    {
        UAV_SpatialTexture[id.xy] = 0;
        return;
    }
	float3 WorldNormal = normalize(SRV_NormalTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).xyz * 2 - 1);

	float NumWeight = 1;
	float4 SpatialColor = SRV_ColorMaskTexture.SampleLevel(Global_point_clamp_sampler, UV, 0);
	uint2 Random = Rand3DPCG16( uint3(id.xy + 0.5, SSR_FrameIndex) ).xy;

	[loop]
	for (int i = 0; i < SSR_NumSpatial; ++i) {


        float2 Offset_UV = UV + (kStackowiakSampleSet4[i] * SSR_FilterResolution.zw * SSR_SpatialRadius);

        if (any(Offset_UV < 0) || any(Offset_UV >= 1)) continue;
        float OffsetDepth = SRV_DepthTexture.SampleLevel(Global_point_clamp_sampler, Offset_UV, 0).r;
        float3 OffsetNormal = normalize(SRV_NormalTexture.SampleLevel(Global_point_clamp_sampler, Offset_UV, 0).xyz * 2 - 1);

		float4 HitColorMask = SRV_ColorMaskTexture.SampleLevel(Global_bilinear_clamp_sampler, Offset_UV, 0);


        float DepthWeight = ScreenSpaceDepthWeight(ScreenSpaceLinearEyeDepth(SceneDepth), ScreenSpaceLinearEyeDepth(OffsetDepth), max(SSR_Thickness, ScreenSpaceLinearEyeDepth(SceneDepth) * 0.01));
        float NormalWeight = ScreenSpaceNormalWeight(WorldNormal, OffsetNormal, 64);
		float Weight = DepthWeight * NormalWeight;
        NumWeight += Weight;

        SpatialColor += HitColorMask * Weight;
	}
	SpatialColor /= max(NumWeight, 0.00001);


    UAV_SpatialTexture[id.xy] = SpatialColor;
}

#define VARIANCE_THRESHOLD 0.0005
static const int2 TemportalOffsets[9] = { int2(-1, -1), int2(0, -1), int2(1, -1), int2(-1, 0), int2(0, 0), int2(1, 0), int2(-1, 1), int2(0, 1), int2(1, 1) };
float ComputeTemporalVariance(float3 History_Radiance, float3 Radiance)
{
    float history_luminance = Rec709Luminance(History_Radiance);
    float luminance = Rec709Luminance(Radiance);
    return abs(history_luminance - luminance) / max(max(history_luminance, luminance), 0.00001);
}

#pragma kernel TemporalFilter
RWTexture2D<float4> UAV_AccmulateTexture;
RWTexture2D<float4> UAV_MomentsTexture;
RWTexture2D<float4> UAV_DepthNormalTexture;
[numthreads(16, 16, 1)]
void TemporalFilter (uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= (uint2)SSR_FilterResolution.xy)) return;
    float2 UV = (id.xy + 0.5) * SSR_FilterResolution.zw;
    float SceneDepth = SRV_DepthTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).r;
    float3 WorldNormal = normalize(SRV_NormalTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).xyz * 2 - 1);
    float4 hitRecord = SRV_HitPDFTexture.SampleLevel(Global_point_clamp_sampler, UV, 0);
    float2 HitMotion = hitRecord.w > 0 ? GetMotionVector(hitRecord.z, hitRecord.xy, Matrix_InvViewProj, Matrix_LastMotionViewProj, Matrix_MotionViewProj) : 0;
    float2 DepthMotion = SRV_MotionTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).xy;

    float4 SampleColors[9];
    float4 CurrColor, PrevColor, MomentA = 0, MomentB = 0;

    [loop]
    for(int i = 0; i < 9; ++i)
    {
        SampleColors[i] = SRV_AliasingTexture.SampleLevel(Global_bilinear_clamp_sampler, UV + (TemportalOffsets[i] * SSR_FilterResolution.zw), 0);
        MomentA += SampleColors[i];
        MomentB += SampleColors[i] * SampleColors[i];
    }

    float4 Mean = MomentA / 9;
    float4 Stddev = sqrt(max(0, (MomentB / 9) - pow2(Mean)));

    CurrColor = SampleColors[4];
    float4 MinColor = Mean - SSR_TemporalScale * Stddev;
    float4 MaxColor = Mean + SSR_TemporalScale * Stddev;
    MinColor = min(MinColor, CurrColor);
    MaxColor = max(MaxColor, CurrColor);

    float2 PrevUV;
    float expectedHistoryDepth;
    ReprojectSurface(UV, SceneDepth, DepthMotion, Matrix_InvViewProj, Matrix_HistoryViewProj, Matrix_MotionViewProj, Matrix_LastMotionViewProj, PrevUV, expectedHistoryDepth);
    float2 RayPrevUV = PrevUV + DepthMotion - HitMotion;
    bool offscreen = any(PrevUV < 0) || any(PrevUV > 1) || any(RayPrevUV < 0) || any(RayPrevUV > 1);

    if (offscreen)
    {
        PrevColor = CurrColor;
    }
    else
    {
        float4 HistoryDepthNormal = SRV_HistoryDepthNormal.SampleLevel(Global_point_clamp_sampler, PrevUV, 0);
        float3 HistoryNormal = HistoryDepthNormal.xyz * 2 - 1;
        float DepthConfidence = HistoryDepthConfidence(SRV_HistoryDepthNormal, PrevUV, expectedHistoryDepth, 3);
        float NormalReject = 1 - saturate(dot(WorldNormal, HistoryNormal));
        float HistoryConfidence = DepthConfidence * saturate(1 - NormalReject * 4);

        float4 RayProject_PrevColor = SRV_HistoryTexture.SampleLevel(Global_point_clamp_sampler, RayPrevUV, 0);
        float4 RayProject_Dist = ( RayProject_PrevColor - Mean ) / max(Stddev, 1e-4);
        float RayProject_Weight = (hitRecord.w > 0 ? 1.0 : 0.0) * exp2(-10 * Rec709Luminance(abs(RayProject_Dist.rgb)));

        float4 DepthProject_PrevColor = SRV_HistoryTexture.SampleLevel(Global_point_clamp_sampler, PrevUV, 0);
        float4 DepthProject_Dist = (DepthProject_PrevColor - Mean) / max(Stddev, 1e-4);
        float DepthProject_Weight = exp2(-10 * Rec709Luminance(abs(DepthProject_Dist.rgb)));

        PrevColor = (RayProject_PrevColor * RayProject_Weight + DepthProject_PrevColor * DepthProject_Weight) / max(RayProject_Weight + DepthProject_Weight, 1e-4);
        PrevColor = clamp(PrevColor, MinColor, MaxColor);
        PrevColor = lerp(CurrColor, PrevColor, HistoryConfidence);
    }

    float motionLength = max(length(HitMotion), length(DepthMotion));
    float BlendWeight = clamp(lerp(SSR_TemporalWeight, 0.0, motionLength * 200.0), 0.0, SSR_TemporalWeight);
    float4 Radiance = max(0, lerp(CurrColor, PrevColor, BlendWeight));
    float Variance = ComputeTemporalVariance(PrevColor.rgb, Radiance.rgb) > VARIANCE_THRESHOLD ? 0 : 1;

    UAV_AccmulateTexture[id.xy] = Radiance;
    UAV_MomentsTexture[id.xy] = float4(Rec709Luminance(Mean.rgb), Rec709Luminance(Stddev.rgb), BlendWeight, Variance);
    UAV_DepthNormalTexture[id.xy] = float4(WorldNormal * 0.5 + 0.5, SceneDepth);
}

static const float Bilateralkernel[25] = { float(1.0f / 256.0f), float(1.0f / 64.0f), float(3.0f / 128.0f), float(1.0f / 64.0f), float(1.0f / 256.0f), float(1.0f / 64.0f), float(1.0f / 16.0f), float(3.0f / 32.0f), float(1.0f / 16.0f), float(1.0f / 64.0f), float(3.0f / 128.0f), float(3.0f / 32.0f), float(9.0f / 64.0f), float(3.0f / 32.0f), float(3.0f / 128.0f), float(1.0f / 64.0f), float(1.0f / 16.0f), float(3.0f / 32.0f), float(1.0f / 16.0f), float(1.0f / 64.0f), float(1.0f / 256.0f), float(1.0f / 64.0f), float(3.0f / 128.0f), float(1.0f / 64.0f), float(1.0f / 256.0f) };
static const int2 BilateralOffset[25] = { int2(-2, -2), int2(-1, -2), int2(0, -2), int2(1, -2), int2(2, -2), int2(-2, -1), int2(-1, -1), int2(0, -1), int2(1, -1), int2(2, -1), int2(-2, 0), int2(-1, 0), int2(0, 0), int2(1, 0), int2(2, 0), int2(-2, 1), int2(-1, 1), int2(0, 1), int2(1, 1), int2(2, 1), int2(-2, 2), int2(-1, 2), int2(0, 2), int2(1, 2), int2(2, 2) };

float SVGF_BilateralRadius, SVGF_ColorWeight, SVGF_NormalWeight, SVGF_DepthWeight;
float4 SVGF_BilateralSize;
Texture2D SRV_InputColor;
RWTexture2D<float4> UAV_BilateralColor;

#pragma kernel BilateralFilter
[numthreads(16, 16, 1)]
void BilateralFilter (uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= (uint2)SVGF_BilateralSize.xy)) return;
	float WeightSum = 0;
	float4 ColorSum = 0;

    float2 UV = (id.xy + 0.5) * SVGF_BilateralSize.zw;
	float4 Color = SRV_AliasingTexture.SampleLevel(Global_bilinear_clamp_sampler, UV, 0);
	float4 Normal = SRV_NormalTexture.SampleLevel(Global_bilinear_clamp_sampler, UV, 0);
	float Depth = ScreenSpaceLinearEyeDepth(SRV_DepthTexture.SampleLevel(Global_point_clamp_sampler, UV, 0).r);

	for(int i = 0; i < 25; i++) {
		float2 OffsetUV = UV + (BilateralOffset[i] * SVGF_BilateralSize.zw * SVGF_BilateralRadius);

		float4 OffsetColor = SRV_AliasingTexture.SampleLevel(Global_bilinear_clamp_sampler, OffsetUV, 0);
        float4 OffsetNormal = SRV_NormalTexture.SampleLevel(Global_bilinear_clamp_sampler, OffsetUV, 0);
        float OffsetDepth = ScreenSpaceLinearEyeDepth(SRV_DepthTexture.SampleLevel(Global_point_clamp_sampler, OffsetUV, 0).r);

		float4 Distance = Normal - OffsetNormal;
		float Distance2 = max( dot(Distance, Distance) / (SVGF_BilateralRadius * SVGF_BilateralRadius), 0);
		float WeightNormal = min( exp(-Distance2 / max(SVGF_NormalWeight, 1e-4)), 1 );
	    float WeightDepth = (SVGF_DepthWeight == 0) ? 0 : abs(Depth - OffsetDepth) / SVGF_DepthWeight;
	    float WeightColor = abs( Rec709Luminance(Color.rgb) - Rec709Luminance(OffsetColor.rgb) ) / max(SVGF_ColorWeight, 1e-4);
        float Weight = exp(0 - max(WeightColor, 0) - max(WeightDepth, 0)) * WeightNormal;

		ColorSum += OffsetColor * Weight * Bilateralkernel[i];
		WeightSum += Weight * Bilateralkernel[i];
	}
	UAV_BilateralColor[id.xy] = ColorSum / WeightSum;
}
